apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task
spec:
  steps:
  - name: check-ubuntu-workingdir
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo $(pwd);
  - name: kube-hunter
    image: aquasec/kube-hunter 
    command: ["/bin/sh", "-c"]
    args:
    - echo $(pwd);